#!/bin/sh
set -euo pipefail

echo "Setting up motd (vmware)"
echo "Welcome to \\R!" > /etc/issue
echo "Kernel \\r" >> /etc/issue
echo "" >> /etc/issue
echo "Use the credentials provided via guest OS customization to log into OS." >> /etc/issue
if test "${CLOUDINIT}" == "1"; then
	echo "Default user: altlinux" >> /etc/issue
fi
echo "Motd setted up"
