#!/bin/sh
set -euo pipefail

echo "Setting up motd (vmware)"

apt-get install -y alt-issue
if test "${TARGET}" == "alt-server"; then
	apt-get install -y alt-issue-server
fi

echo "Use the credentials provided via guest OS customization to log into OS." >> /etc/issue.d/01vmware.issue

echo "Motd setted up"
